Add Dockerfile and ghidra_deploy.sh
louiskyee/OpCodeReverseTool pull request #6
Opened 2024-07-29 07:53 UTC by skyblue302

2024-07-29 09:47 UTC, louiskyee commented on deployment-scripts/ghidra_deploy/ghidra_deploy.sh
> +export SUDO_PASS="ghidrauser"
Problem: The password is hardcoded in the script, which poses a security risk.
Suggestion: Use a variable to store the password and ensure the script is stored in a secure location. Consider reading the password from a secure location, such as an environment variable.

2024-07-29 10:02 UTC, louiskyee requested changes
Here is the major issues and suggestions for the `ghidra_deploy.sh` script:

1. **Hardcoded Password**
   - **Problem**: The password is hardcoded in the script, posing a security risk.
   - **Suggestion**: Use a variable to store the password and ensure the script is stored in a secure location. Consider reading the password from a secure location, such as an environment variable.

   ```bash
   USER="ghidrauser"
   PASS="ghidrauser"
   echo "$USER:$PASS" | sudo chpasswd
   ```

2. **Repeated sudo Password Input**
   - **Problem**: The command `echo $SUDO_PASS | sudo -S` is repeated multiple times, which is inefficient.
   - **Suggestion**: Define a function to run commands with sudo and use it throughout the script.

   ```bash
   run_sudo() {
       echo $PASS | sudo -S "$@"
   }
   run_sudo apt-get update
   run_sudo apt-get install -y git make wget unzip python3 python3-pip gcc g++ python3-venv python-is-python3 tar
   ```

3. **Repeated JAVA_HOME Setup**
   - **Problem**: The `JAVA_HOME` setup is repeated and uses two different methods.
   - **Suggestion**: Combine the setup steps and use a consistent method.

   ```bash
   export JAVA_HOME=/home/$USER/jdk-17
   export PATH=$JAVA_HOME/bin:$PATH
   ```

4. **Lack of Error Handling**
   - **Problem**: The script lacks error handling for download and installation steps, which might continue execution even if a step fails.
   - **Suggestion**: Add error checking after each critical step to ensure successful execution.

   ```bash
   wget https://download.oracle.com/java/17/archive/jdk-17.0.7_linux-x64_bin.tar.gz -P /home/$USER/tmp || { echo "Failed to download JDK"; exit 1; }
   ```

5. **Persisting Environment Variables**
   - **Problem**: Environment variables should be persisted in the `.profile` file to ensure they are available in new shell sessions.
   - **Suggestion**: Consolidate the commands to append to the `.profile` file.

   ```bash
   echo -e "export JAVA_HOME=$JAVA_HOME\nexport GRADLE_HOME=$GRADLE_HOME\nexport PATH=\$JAVA_HOME/bin:\$GRADLE_HOME/bin:\$PATH" >> /home/$USER/.profile
   source /home/$USER/.profile
   ```

6. **GHIDRA_HOME Environment Variable Setup**
   - **Problem**: The setup for `GHIDRA_HOME` should be consistent with previous setups and check if it is set correctly.
   - **Suggestion**: Combine environment variable setup steps.

   ```bash
   export GHIDRA_HOME=/home/$USER/ghidra/ghidra_10.3.1_PUBLIC
   ```

7. **Repeated Download and Extraction**
   - **Problem**: The download and extraction steps lack error handling and should use variables to simplify paths.
   - **Suggestion**: Add error handling and use variables for paths.

   ```bash
   GHIDRA_ARCHIVE=/home/$USER/tmp/ghidra_10.3.1_PUBLIC_20230614.zip
   wget https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.3.1_build/ghidra_10.3.1_PUBLIC_20230614.zip -P /home/$USER/tmp || { echo "Failed to download Ghidra"; exit 1; }
   unzip $GHIDRA_ARCHIVE -d /home/$USER/ghidra || { echo "Failed to unzip Ghidra"; exit 1; }
   ```

8. **Activating Virtual Environment**
   - **Problem**: Creating and activating the virtual environment lacks error handling.
   - **Suggestion**: Check if the virtual environment is created and activate it accordingly.

   ```bash
   python3 -m venv $GHIDRA_HOME/venv || { echo "Failed to create virtual environment"; exit 1; }
   if [ -f "$GHIDRA_HOME/venv/bin/activate" ]; then
       source $GHIDRA_HOME/venv/bin/activate
   else
       echo "Virtual environment activation script not found."
       exit 1
   fi
   ```

9. **Missing Cleanup Step**
   - **Problem**: The script does not clean up temporary files after execution.
   - **Suggestion**: Add a cleanup step at the end of the script.

   ```bash
   # Clean up temporary files
   rm -rf /home/$USER/tmp
   ```

2024-07-29 10:02 UTC, bolin8017 commented on deployment-scripts/ghidra_deploy/ghidra_deploy.sh
> +echo "ghidrauser:ghidrauser" | sudo chpasswd
Problem: The password is hardcoded in the script, which poses a security risk.
Suggestion: Use a variable to store the password and ensure the script is stored in a secure location. Consider reading the password from a secure location, such as an environment variable.

2024-07-29 10:02 UTC, bolin8017 commented on deployment-scripts/ghidra_deploy/ghidra_deploy.sh
> +echo $SUDO_PASS | sudo -S apt-get install -y git make wget unzip python3 python3-pip gcc g++ python3-venv python-is-python3 tar
Problem: The command echo $SUDO_PASS | sudo -S is repeated multiple times, which is not efficient.
Suggestion: Define a function to run commands with sudo and use it throughout the script.

2024-07-29 10:02 UTC, bolin8017 commented on deployment-scripts/ghidra_deploy/ghidra_deploy.sh
> +echo "JAVA_HOME set to $JAVA_HOME"
Problem: The JAVA_HOME setup is repeated and uses two different methods.
Suggestion: Combine the setup steps and use a consistent method.

2024-07-29 10:02 UTC, bolin8017 commented on deployment-scripts/ghidra_deploy/ghidra_deploy.sh
> +export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
Problem: Environment variables should be persisted in the .profile file to ensure they are available in new shell sessions.
Suggestion: Consolidate the commands to append to the .profile file.

2024-10-13 07:56 UTC, louiskyee approved these changes
Thank you for updating this Ghidra deployment file and resolving the issues from the previous PR. I will merge this file into the main branch. I greatly appreciate your kind assistance.

2024-10-13 07:56 UTC, merged